require("mason").setup()

require("mason-tool-installer").setup({
	ensure_installed = {
		-- LSP servers
		"basedpyright",
		"bash-language-server",
		"biome",
		"clangd",
		"cmake-language-server",
		"css-lsp",
		"docker-compose-language-service",
		"docker-language-server",
		"dockerfile-language-server",
		"emmet-language-server",
		"lua-language-server",
		"gopls",
		-- "haskell-language-server",
		"html-lsp",
		"htmx-lsp",
		"jinja-lsp",
		"json-lsp",
		"lemminx",
		"marksman",
		"powershell-editor-services",
		--"roslyn-language-server",
		"ruff",
		"rust-analyzer",
		"sqlls",
		"svelte-language-server",
		"tailwindcss-language-server",
		"taplo",
		"ty",
		"typescript-language-server",
		"yaml-language-server",
		"zls",

		-- Formatters
		"stylua",
		"prettier",
		"clang-format",
		"goimports",
		"yamlfmt",
		"xmlformatter",
	},

	auto_update = true,
	run_on_start = true,
})

vim.lsp.enable({
	"basedpyright",
	"bashls",
	"biome",
	"clangd",
	"cmake",
	"cssls",
	"docker_compose_language_service",
	"docker_language_server",
	"dockerls",
	"emmet_language_server",
	"lua_ls",
	"gopls",
	"html",
	"htmx",
	"jinja_lsp",
	"jsonls",
	"lemminx",
	"marksman",
	"powershell_es",
	"ruff",
	"rust_analyzer",
	"sqlls",
	"svelte",
	"tailwindcss",
	"taplo",
	"ty",
	"ts_ls",
	"yamlls",
	"zls",
})
